name: EDeals

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  APP_NAME: edeals_web
  IN_PORT: 5003
  OUT_PORT: 5003
  ENVIRONMENT: Production
  SSH_KEY: ${{ secrets.prod_ssh_key }}
  SSH_USER: ${{ secrets.prod_ssh_user }}
  SSH_IP: ${{ secrets.prod_ssh_ip }}
  VERSION_NUMBER: ${{ github.run_number }}
  DOCKER_ENV_FILE: ${{ secrets.prod_docker_env_file }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js App
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install
        
      - name: Build Docker Image
          run: |
            docker build -t ${{ env.APP_NAME }}:${{env.VERSION_NUMBER}} .
            docker save -o ${{ env.APP_NAME }}.tar ${{ env.APP_NAME }}:${{env.VERSION_NUMBER}}
        - name: Transfer the Docker Image
          uses: appleboy/scp-action@master
          with:
            host: ${{env.SSH_IP}}
            port: 22
            username: ${{env.SSH_USER}}
            key: ${{env.SSK_KEY}}
            source: "${{ env.APP_NAME }}.tar"
            target: "/home/${{env.SSH_USER}}"

  run-container:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Connect trough SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{env.SSH_IP}}
          username: ${{env.SSH_USER}}
          key: ${{env.SSK_KEY}}
          script: |
            echo "${{ env.DOCKER_ENV_FILE }}" > ./docker.env
            docker image prune -a -f
            docker load -i ${{ env.APP_NAME }}.tar
            docker rm -f ${{env.APP_NAME}}
            docker run -d -p ${{env.OUT_PORT}}:${{env.IN_PORT}} --network edeals --name ${{env.APP_NAME}} --env-file ./docker.env ${{env.APP_NAME}}:${{env.VERSION_NUMBER}}
