name: EDeals

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  APP_NAME: edeals_web
  IN_PORT: 5003
  OUT_PORT: 5003
  ENVIRONMENT: Production
  SSH_KEY: ${{ secrets.prod_ssh_key }}
  SSH_USER: ${{ secrets.prod_ssh_user }}
  SSH_IP: ${{ secrets.prod_ssh_ip }}
  VERSION_NUMBER: ${{ github.run_number }}
  DOCKER_ENV_FILE: ${{ secrets.prod_docker_env_file }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node App
        run: |
          npm install
          npm run build
      # - name: Build Docker Image
      #   run: |
      #     docker build -t ${{ env.APP_NAME }}:${{env.VERSION_NUMBER}} .
      #     docker save -o ${{ env.APP_NAME }}.tar ${{ env.APP_NAME }}:${{env.VERSION_NUMBER}}
      - name: Transfer the build artifacts
        uses: appleboy/scp-action@master
        with:
          host: ${{env.SSH_IP}}
          port: 22
          username: ${{env.SSH_USER}}
          key: ${{env.SSK_KEY}}
          source: "build"
          target: "/home/${{env.SSH_USER}}/${{ env.APP_NAME }}"

  run-container:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Connect trough SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{env.SSH_IP}}
          username: ${{env.SSH_USER}}
          key: ${{env.SSK_KEY}}
          script: |
            echo "${{ env.DOCKER_ENV_FILE }}" > ./docker.env
            docker stop ${{ env.APP_NAME }} || true
            docker rm ${{ env.APP_NAME }} || true
            docker run -d -p ${{env.OUT_PORT}}:${{env.IN_PORT}} --network edeals --name ${{ env.APP_NAME }} --env-file ./docker.env -v /home/${{ env.SSH_USER }}/${{ env.APP_NAME }}:/usr/share/nginx/html:ro nginx:latest
